import type { Role } from '../types';

export const PREDEFINED_ROLE_TEMPLATES: Omit<Role, 'id'>[] = [
  { name: 'Maire', color: '#F59E0B', lives: 1, isUnique: true, teamId: null, tags: [], isSelectableForDistribution: false, distributionQuantity: 1, defaultCount: 1, minCount: 0, maxCount: 99, isFiller: false, isMinMandatory: false, description: 'A un vote supplémentaire en cas d\'égalité' },
  { name: 'Sheriff', color: '#3B82F6', lives: 1, isUnique: true, teamId: null, tags: [], isSelectableForDistribution: false, distributionQuantity: 1, defaultCount: 1, minCount: 0, maxCount: 99, isFiller: false, isMinMandatory: false, description: 'Peut protéger un joueur chaque nuit' },
  { name: 'Docteur', color: '#10B981', lives: 1, isUnique: true, teamId: null, tags: [], isSelectableForDistribution: false, distributionQuantity: 1, defaultCount: 1, minCount: 0, maxCount: 99, isFiller: false, isMinMandatory: false, description: 'Peut soigner un joueur chaque nuit' },
  { name: 'Détective', color: '#8B5CF6', lives: 1, isUnique: true, teamId: null, tags: [], isSelectableForDistribution: false, distributionQuantity: 1, defaultCount: 1, minCount: 0, maxCount: 99, isFiller: false, isMinMandatory: false, description: 'Peut vérifier l\'identité d\'un joueur' },
  { name: 'Garde du Corps', color: '#6B7280', lives: 1, isUnique: true, teamId: null, tags: [], isSelectableForDistribution: false, distributionQuantity: 1, defaultCount: 1, minCount: 0, maxCount: 99, isFiller: false, isMinMandatory: false, description: 'Se sacrifie pour protéger un joueur' },
  { name: 'Villageois Simple', color: '#22C55E', lives: 1, isUnique: false, teamId: null, tags: [], isSelectableForDistribution: false, distributionQuantity: 1, defaultCount: 1, minCount: 0, maxCount: 99, isFiller: false, isMinMandatory: false, description: 'Simple villageois sans pouvoir spécial' },
  { name: 'Loup Alpha', color: '#EF4444', lives: 1, isUnique: true, teamId: null, tags: [], isSelectableForDistribution: false, distributionQuantity: 1, defaultCount: 1, minCount: 0, maxCount: 99, isFiller: false, isMinMandatory: false, description: 'Chef des loups, se réveille en premier' },
  { name: 'Loup-Garou', color: '#7F1D1D', lives: 1, isUnique: false, teamId: null, tags: [], isSelectableForDistribution: false, distributionQuantity: 1, defaultCount: 1, minCount: 0, maxCount: 99, isFiller: false, isMinMandatory: false, description: 'Dévore un villageois chaque nuit' },
  { name: 'Traître', color: '#A855F7', lives: 1, isUnique: true, teamId: null, tags: [], isSelectableForDistribution: false, distributionQuantity: 1, defaultCount: 1, minCount: 0, maxCount: 99, isFiller: false, isMinMandatory: false, description: 'Change de camp au milieu du jeu' },
  { name: 'Voyante', color: '#EC4899', lives: 1, isUnique: true, teamId: null, tags: [], isSelectableForDistribution: false, distributionQuantity: 1, defaultCount: 1, minCount: 0, maxCount: 99, isFiller: false, isMinMandatory: false, description: 'Voit le rôle d\'un joueur chaque nuit' },
  { name: 'Sorcière', color: '#06B6D4', lives: 1, isUnique: true, teamId: null, tags: [], isSelectableForDistribution: false, distributionQuantity: 1, defaultCount: 1, minCount: 0, maxCount: 99, isFiller: false, isMinMandatory: false, description: 'Possède une potion de vie et une de mort' },
  { name: 'Chasseur', color: '#DC2626', lives: 1, isUnique: true, teamId: null, tags: [], isSelectableForDistribution: false, distributionQuantity: 1, defaultCount: 1, minCount: 0, maxCount: 99, isFiller: false, isMinMandatory: false, description: 'Emporte un joueur dans sa mort' },
  { name: 'Cupidon', color: '#F472B6', lives: 1, isUnique: true, teamId: null, tags: [], isSelectableForDistribution: false, distributionQuantity: 1, defaultCount: 1, minCount: 0, maxCount: 99, isFiller: false, isMinMandatory: false, description: 'Lie deux joueurs amoureux la première nuit' },
  { name: 'Ancien', color: '#92400E', lives: 2, isUnique: true, teamId: null, tags: [], isSelectableForDistribution: false, distributionQuantity: 1, defaultCount: 1, minCount: 0, maxCount: 99, isFiller: false, isMinMandatory: false, description: 'Résiste à deux attaques de loups' },
  { name: 'Salvateur', color: '#2563EB', lives: 1, isUnique: true, teamId: null, tags: [], isSelectableForDistribution: false, distributionQuantity: 1, defaultCount: 1, minCount: 0, maxCount: 99, isFiller: false, isMinMandatory: false, description: 'Protège un joueur de la mort chaque nuit' },
];
