import type { TagModel } from '../types';

export const PREDEFINED_TAG_TEMPLATES: Omit<TagModel, 'id'>[] = [
  { name: 'Loup-Garou', color: '#6B7280', icon: 'Moon', points: null, lives: null, votes: null, uses: null, callOrderDay: null, callOrderNight: 1, autoDeleteOnZeroUses: false, description: 'Se réveille la nuit pour dévorer un villageois', showInTooltip: true, showInGameTab: true, showOnSmartphone: false, showPastille: false, visibleInWiki: false },
  { name: 'Voyante', color: '#8B5CF6', icon: 'Eye', points: null, lives: null, votes: null, uses: null, callOrderDay: null, callOrderNight: 2, autoDeleteOnZeroUses: false, description: 'Se réveille la nuit pour découvrir l\'identité d\'un joueur', showInTooltip: true, showInGameTab: true, showOnSmartphone: false, showPastille: false, visibleInWiki: false },
  { name: 'Chasseur', color: '#EF4444', icon: 'Crosshair', points: null, lives: null, votes: null, uses: 1, callOrderDay: null, callOrderNight: null, autoDeleteOnZeroUses: true, description: 'Peut emporter un joueur dans sa mort', showInTooltip: true, showInGameTab: true, showOnSmartphone: false, showPastille: false, visibleInWiki: false },
  { name: 'Villageois', color: '#10B981', icon: 'Users', points: null, lives: null, votes: null, uses: null, callOrderDay: null, callOrderNight: null, autoDeleteOnZeroUses: false, description: 'Simple villageois sans pouvoir', showInTooltip: true, showInGameTab: true, showOnSmartphone: false, showPastille: false, visibleInWiki: false },
  { name: 'Sorcière', color: '#06B6D4', icon: 'FlaskConical', points: null, lives: null, votes: null, uses: null, callOrderDay: null, callOrderNight: 3, autoDeleteOnZeroUses: false, description: 'Possède une potion de vie et une potion de mort', showInTooltip: true, showInGameTab: true, showOnSmartphone: false, showPastille: false, visibleInWiki: false },
  { name: 'Cupidon', color: '#EC4899', icon: 'Heart', points: null, lives: null, votes: null, uses: 1, callOrderDay: null, callOrderNight: 4, autoDeleteOnZeroUses: true, description: 'Désigne deux joueurs amoureux', showInTooltip: true, showInGameTab: true, showOnSmartphone: false, showPastille: false, visibleInWiki: false },
  { name: 'Voleur', color: '#F59E0B', icon: 'Hand', points: null, lives: null, votes: null, uses: 1, callOrderDay: null, callOrderNight: null, autoDeleteOnZeroUses: true, description: 'Peut voler le rôle d\'un joueur mort', showInTooltip: true, showInGameTab: true, showOnSmartphone: false, showPastille: false, visibleInWiki: false },
  { name: 'Ancien', color: '#92400E', icon: 'Crown', points: null, lives: 2, votes: null, uses: null, callOrderDay: null, callOrderNight: null, autoDeleteOnZeroUses: false, description: 'Résiste à deux attaques de loups-garous', showInTooltip: true, showInGameTab: true, showOnSmartphone: false, showPastille: false, visibleInWiki: false },
  { name: 'Enfant Sauvage', color: '#84CC16', icon: 'Baby', points: null, lives: null, votes: null, uses: 1, callOrderDay: null, callOrderNight: null, autoDeleteOnZeroUses: true, description: 'Choisit un modèle au début du jeu', showInTooltip: true, showInGameTab: true, showOnSmartphone: false, showPastille: false, visibleInWiki: false },
  { name: 'Comédien', color: '#A855F7', icon: 'Theater', points: null, lives: null, votes: null, uses: null, callOrderDay: null, callOrderNight: null, autoDeleteOnZeroUses: false, description: 'Peut se faire passer pour un autre rôle', showInTooltip: true, showInGameTab: true, showOnSmartphone: false, showPastille: false, visibleInWiki: false },
  { name: 'Mort', color: '#6B7280', icon: 'Skull', points: null, lives: null, votes: null, uses: null, callOrderDay: null, callOrderNight: null, autoDeleteOnZeroUses: false, description: 'Joueur décédé', showInTooltip: true, showInGameTab: true, showOnSmartphone: false, showPastille: false, visibleInWiki: false },
  { name: 'Amoureux', color: '#EC4899', icon: 'HeartHandshake', points: null, lives: null, votes: null, uses: null, callOrderDay: null, callOrderNight: null, autoDeleteOnZeroUses: false, description: 'Lié à un autre joueur par l\'amour', showInTooltip: true, showInGameTab: true, showOnSmartphone: false, showPastille: false, visibleInWiki: false },
  { name: 'Salvateur', color: '#3B82F6', icon: 'Shield', points: null, lives: null, votes: null, uses: null, callOrderDay: null, callOrderNight: 5, autoDeleteOnZeroUses: false, description: 'Protège un joueur chaque nuit', showInTooltip: true, showInGameTab: true, showOnSmartphone: false, showPastille: false, visibleInWiki: false },
  { name: 'Joueur de Flûte', color: '#7C3AED', icon: 'Music', points: null, lives: null, votes: null, uses: null, callOrderDay: null, callOrderNight: 6, autoDeleteOnZeroUses: false, description: 'Charme des joueurs pour gagner seul', showInTooltip: true, showInGameTab: true, showOnSmartphone: false, showPastille: false, visibleInWiki: false },
  { name: 'Renard', color: '#F97316', icon: 'Fox', points: null, lives: 3, votes: null, uses: null, callOrderDay: null, callOrderNight: null, autoDeleteOnZeroUses: false, description: 'Vérifie si un groupe contient un loup-garou', showInTooltip: true, showInGameTab: true, showOnSmartphone: false, showPastille: false, visibleInWiki: false },
];
