import type { EffectHandler } from '../types';

// Player effects
import {
  handleKillPlayer,
  handleResurrectPlayer,
  handleKillAllPlayers,
  handleResurrectAllPlayers,
  handleSleepPlayer,
  handleWakePlayer,
  handleSwitchSleepPlayer,
  handleSleepAllPlayers,
  handleWakeAllPlayers,
  handleSelectPlayer,
  handlePingPlayer,
  handleMovePlayerToGraveyard,
  handleMoveCibleToGraveyard,
  handleGatherPlayers,
  handleChangePlayerShape,
  handleClearPlayer,
  handleRemovePlayerRole,
  handleBlindPlayer,
  handleRevealPlayerRole,
  handleTogglePlayerPastille,
  handleForceSmartphoneTab,
  handleVibrateSmartphone,
  handleLockSmartphone,
  handleShowAllPlayers,
  handleHideAllPlayers,
  handleShowPlayerImage,
  handleHidePlayerImage,
  handleShowRoleImage,
  handleHideRoleImage,
  handleShowPlayerTooltip,
  handleHidePlayerTooltip,
  handleShowTagTooltip,
  handleHideTagTooltip,
  handleShowRoleColor,
  handleHideRoleColor,
  handleShowTimerOnSmartphone,
  handleHideTimerOnSmartphone,
  handleShowDiceOnSmartphone,
  handleHideDiceOnSmartphone,
} from './player-effects';

// Tag effects
import {
  handleAssignTag,
  handleRemoveTag,
  handleDeleteAllTags,
  handleDeleteAllPlayerTags,
  handleDeleteSelectionPastilles,
  handleAssignTagToRole,
  handleRemoveTagFromRole,
  handleIncrementTagValue,
  handleSpreadTag,
  handleSwapPlayerTags,
} from './tag-effects';

// Role/Team effects
import {
  handleAssignRole,
  handleSwapPlayerRole,
  handleStealRoleAndKill,
  handleSetFakeRole,
  handleDistributeRoles,
  handleAssignTeam,
  handleAssignTeamToRole,
  handleClearPlayerTeam,
  handleJoinTargetTeam,
  handleShuffleTeams,
} from './role-team-effects';

// UI/Misc effects
import {
  handleWait,
  handleStopExecution,
  handleResetBoard,
  handleNextPhase,
  handlePreviousPhase,
  handleResetCycle,
  handleSetCycleDayNight,
  handleSetCycleTurn,
  handleSetCycleNone,
  handleSetDayNumber,
  handleSetNightNumber,
  handleAlertPlayerName,
  handleAlertVariable,
  handlePopupPlayer,
  handlePlaySound,
  handleShowHandout,
  handleSendPrivateMessage,
  handleAddSystemLog,
  handleSetRoomBackground,
  handleSetRoomColor,
  handleRollDice,
  handlePlayParticleEffect,
  handleToggleActionEnabled,
  handleTriggerAction,
  handleSendPollToSmartphone,
  handleSendGroupVoteToSmartphone,
  handleSelectCallOrderPlayer,
  handleIncrementCallOrder,
  handleDecrementCallOrder,
  handleResetCallOrder,
} from './ui-misc-effects';

// Werewolf-specific effects
import {
  handleCreateCouple,
  handleKillPartner,
  handleRandomSelect,
  handleCheckRole,
  handleRevealRoleToGM,
  handleInfectPlayer,
  handleCurePlayer,
} from './werewolf-effects';

/**
 * Registry mapping effect types to their handlers
 */
export const effectRegistry: Record<string, EffectHandler> = {
  // Player effects
  killPlayer: handleKillPlayer,
  resurrectPlayer: handleResurrectPlayer,
  resurrectAllPlayers: handleResurrectAllPlayers,
  sleepPlayer: handleSleepPlayer,
  wakePlayer: handleWakePlayer,
  switchSleepPlayer: handleSwitchSleepPlayer,
  sleepAllPlayers: handleSleepAllPlayers,
  wakeAllPlayers: handleWakeAllPlayers,
  selectPlayer: handleSelectPlayer,
  pingPlayer: handlePingPlayer,
  movePlayerToGraveyard: handleMovePlayerToGraveyard,
  moveCibleToGraveyard: handleMoveCibleToGraveyard,
  gatherPlayers: handleGatherPlayers,
  changePlayerShape: handleChangePlayerShape,
  clearPlayer: handleClearPlayer,
  removePlayerRole: handleRemovePlayerRole,
  blindPlayer: handleBlindPlayer,
  revealPlayerRole: handleRevealPlayerRole,
  hidePlayerRole: handleRevealPlayerRole, // Same handler, different type
  togglePlayerPastille: handleTogglePlayerPastille,
  forceSmartphoneTab: handleForceSmartphoneTab,
  vibrateSmartphone: handleVibrateSmartphone,
  lockSmartphone: handleLockSmartphone,
  showAllPlayers: handleShowAllPlayers,
  hideAllPlayers: handleHideAllPlayers,
  showPlayerImage: handleShowPlayerImage,
  hidePlayerImage: handleHidePlayerImage,
  showRoleImage: handleShowRoleImage,
  hideRoleImage: handleHideRoleImage,
  showPlayerTooltip: handleShowPlayerTooltip,
  hidePlayerTooltip: handleHidePlayerTooltip,
  showTagTooltip: handleShowTagTooltip,
  hideTagTooltip: handleHideTagTooltip,
  showRoleColor: handleShowRoleColor,
  hideRoleColor: handleHideRoleColor,
  showTimerOnSmartphone: handleShowTimerOnSmartphone,
  hideTimerOnSmartphone: handleHideTimerOnSmartphone,
  showDiceOnSmartphone: handleShowDiceOnSmartphone,
  hideDiceOnSmartphone: handleHideDiceOnSmartphone,
  incrementCallOrder: handleIncrementCallOrder,
  decrementCallOrder: handleDecrementCallOrder,
  resetCallOrder: handleResetCallOrder,

  // Tag effects
  assignTag: handleAssignTag,
  removeTag: handleRemoveTag,
  deleteAllTags: handleDeleteAllTags,
  deleteAllPlayerTags: handleDeleteAllPlayerTags,
  deleteSelectionPastilles: handleDeleteSelectionPastilles,
  assignTagToRole: handleAssignTagToRole,
  removeTagFromRole: handleRemoveTagFromRole,
  incrementTagValue: handleIncrementTagValue,
  spreadTag: handleSpreadTag,
  swapPlayerTags: handleSwapPlayerTags,

  // Role/Team effects
  assignRole: handleAssignRole,
  swapPlayerRole: handleSwapPlayerRole,
  stealRoleAndKill: handleStealRoleAndKill,
  setFakeRole: handleSetFakeRole,
  distributeRoles: handleDistributeRoles,
  assignTeam: handleAssignTeam,
  assignTeamToRole: handleAssignTeamToRole,
  clearPlayerTeam: handleClearPlayerTeam,
  joinTargetTeam: handleJoinTargetTeam,
  shuffleTeams: handleShuffleTeams,

  // UI/Misc effects
  wait: handleWait,
  stopExecution: handleStopExecution,
  resetBoard: handleResetBoard,
  nextPhase: handleNextPhase,
  previousPhase: handlePreviousPhase,
  resetCycle: handleResetCycle,
  setCycleDayNight: handleSetCycleDayNight,
  setCycleTurn: handleSetCycleTurn,
  setCycleNone: handleSetCycleNone,
  setDayNumber: handleSetDayNumber,
  setNightNumber: handleSetNightNumber,
  alertPlayerName: handleAlertPlayerName,
  alertVariable: handleAlertVariable,
  popupVariable: handleAlertVariable,
  popupPlayer: handlePopupPlayer,
  playSound: handlePlaySound,
  showHandout: handleShowHandout,
  sendPrivateMessage: handleSendPrivateMessage,
  addSystemLog: handleAddSystemLog,
  setRoomBackground: handleSetRoomBackground,
  setRoomColor: handleSetRoomColor,
  rollDice: handleRollDice,
  playParticleEffect: handlePlayParticleEffect,
  toggleActionEnabled: handleToggleActionEnabled,
  triggerAction: handleTriggerAction,
  sendPollToSmartphone: handleSendPollToSmartphone,
  sendGroupVoteToSmartphone: handleSendGroupVoteToSmartphone,
  selectCallOrderPlayer: handleSelectCallOrderPlayer,

  // Werewolf-specific effects
  createCouple: handleCreateCouple,
  killPartner: handleKillPartner,
  randomSelect: handleRandomSelect,
  checkRole: handleCheckRole,
  revealRoleToGM: handleRevealRoleToGM,
  infectPlayer: handleInfectPlayer,
  curePlayer: handleCurePlayer,
};

/**
 * Get handler for effect type
 */
export function getEffectHandler(effectType: string): EffectHandler | undefined {
  return effectRegistry[effectType];
}
